### PR TITLE
Update to the latest upstream for the jasmine json parser

### PR DESCRIPTION
**Pull request by amshinde**
The code base includes the source code for jsmn.
This is an old version that needs to be updated.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
@amshinde  I think you should add ``` fixes #28 ``` in your commit message

**Comment by amshinde** [comment]
@devimc Done

**Comment by devimc** [comment]
@amshinde thanks

**Comment by devimc** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/hyperstart/pull-request/29/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/hyperstart) [Approved with PullApprove](https://pullapprove.com/clearcontainers/hyperstart/pull-request/29/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/hyperstart)

**Pull request merged**
