### PR TITLE
Support for stateless systems for retrieving user/group info

### PR DESCRIPTION
**Pull request by amshinde**
This fixes a bug (https://github.com/01org/cc-oci-runtime/issues/649) seen on clearlinux docker image, since hyperstart was just parsing /etc files causing runtime hangs.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
lgtm

**Comment by sameo** [comment]
LGTM

**Comment by jcvenegas** [comment]
lgtm

**Comment by gorozco1** [comment]
lgtm

**Comment by sameo** [comment]
@jcvenegas Could we please generate a new containers image with this hyperstart fix ?

**Comment by jcvenegas** [comment]
@sameo  PR in cc-oci-runtime

**Pull request merged**
